name: campeonato_brasileiro_flutter
description: App sobre o campeonato brasileiro de futebol

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  google_fonts: ^2.1.0
  intl: ^0.17.0
  percent_indicator: ^3.0.1
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.9

  globo_esporte_api:
    path: packages/globo_esporte_api


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.4
  bloc_test: ^8.1.0
  mocktail: ^0.1.4
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
     - assets/icon/icon.png