name: globo_esporte_api
description: A new Flutter package project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0
  retrofit: ^2.0.1

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^4.1.4
  retrofit_generator: ^2.0.1
  test: ^1.16.4
  mock_web_server: ^5.0.0-nullsafety.1
